### ISSUE TITLE
Create a MQTT topic to "reset to factory defaults"

### ISSUE THREAD

**Issue by johnwalicki** [openeew/openeew-firmware#12]
The dashboard will implement a "Remove your sensor from the OpenEEW network" button.  It promises that your sensor will no longer contribute data.
- The dashboard could delete the Cloudant record which would wipe the uuid ownership / latitude / longitude / what regional network it belongs to.
- That would not stop the device from sending data however....  The device doesn't know - its stateless.
- The dashboard could send the MQTT command to turn off the ADXL accelerometer so it doesn't record/send data.  When the device restarts, It will start sending data again.
-  Create a MQTT topic to "reset to factory defaults"  - It would remove all WiFi SSID/password from NVM ram.  That would force the device into SmartConfig Provisioning mode.

**Comment by johnwalicki** [comment]
Todos:

- [ ] Test the feature by sending remote MQTT topic to the OpenEEW sensor
- [ ] Update the Node-RED device orchestration dashboard
- [ ] Push the container to device-mgmt.openeew.com
- [ ] Update the firmware.md to show examples of the factoryreset topic.

**Comment by johnwalicki** [comment]
The topic will be
`iot-2/cmd/factoryreset/fmt/json`
There will be *no* stringified json key/value pair passed as part of this topic. 
`{}`

**Comment by johnwalicki** [comment]
Once the device is in SmartConfig Provisioning mode, the mobile app can be used to connect it to a different WiFi network and register it again (potentially under a different email address / user)

**Comment by johnwalicki** [comment]
In addition to clearing the NVM of WiFi networks, a Factory Reset implies a restart.
The device will clear NVM, restart, boot to SmartConfig.

**Comment by johnwalicki** [comment]
- [] Test the feature by sending remote MQTT topic to the OpenEEW sensor

```
Message arrived [iot-2/cmd/factoryreset/fmt/json] : {}
Remote message received to factory reset the device.
Clear all stored networks from NVM
All networks have been erased
Restarting Device...
WiFi Stopped
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8

OpenEEW Sensor Application
ESP32 WiFi interface ready
Stored networks : 0
ESP32 WiFi started
Completed scan for access points
WiFi Network scan done
5 network(s) found
1: ssidlisthere
ESP32 WiFi interface ready
Found no matches for saved networks
ESP32 WiFi interface ready
ESP32 WiFi started
WiFi Stopped
Waiting for SmartConfig.
```

**Comment by johnwalicki** [comment]
This issue will be closed by https://github.com/openeew/openeew-firmware/commit/0d4e200078b28b9a8e727cee42526c12327be16a

**Comment by neilh10** [comment]
Thats excellent addition.
